const { createClient } = require('@libsql/client');

const db = createClient({
  url: process.env.TURSO_DATABASE_URL,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

const scholarships = [
  // UK
  ['Rhodes Scholarship', 'rhodes-scholarship', 'United Kingdom', 'united-kingdom', 'scholarship', 'Masters,PhD', 'full', 'Full funding', 'October 2025', 'The Rhodes Scholarship is the oldest and most celebrated international fellowship award in the world, enabling outstanding young people to study at Oxford.', 'Academic excellence, leadership potential, commitment to service. Age 18-24 for most countries.', 'Full tuition, living stipend, airfare, health insurance', 'All disciplines', 'University of Oxford', 'United Kingdom', 'https://rhodeshouse.ox.ac.uk', 1, 1],
  ['GREAT Scholarship UK', 'great-scholarship-uk', 'United Kingdom', 'united-kingdom', 'scholarship', 'Masters', 'partial', '£10,000 minimum', 'January 2026', 'The GREAT Scholarship programme offers scholarships for students from selected countries to study a postgraduate degree in the UK.', 'Must be a citizen of an eligible country. Applying to a participating UK university.', 'Minimum £10,000 towards tuition fees', 'Various disciplines', 'Various UK Universities', 'United Kingdom', 'https://study-uk.britishcouncil.org', 1, 0],
  ['Edinburgh Global Research Scholarship', 'edinburgh-global-research-scholarship', 'United Kingdom', 'united-kingdom', 'scholarship', 'PhD', 'partial', 'Tuition fee waiver', 'March 2026', 'The University of Edinburgh offers competitive scholarships for outstanding PhD applicants from outside the EU/UK.', 'Must have applied to PhD at Edinburgh. Exceptional academic record required.', 'Tuition fee difference between home and international rates', 'All research disciplines', 'University of Edinburgh', 'United Kingdom', 'https://ed.ac.uk/student-funding', 0, 0],

  // USA
  ['Hubert Humphrey Fellowship', 'hubert-humphrey-fellowship', 'United States', 'united-states', 'fellowship', 'Non-degree', 'full', 'Full funding', 'October 2025', 'The Hubert H. Humphrey Fellowship Program brings accomplished mid-career professionals to the US for a year of professional development.', 'Mid-career professional with 5+ years experience. Leadership potential. Returning to home country after.', 'Tuition, living stipend, travel, health insurance', 'Public policy, education, public health, agriculture', 'Various US Universities', 'United States', 'https://humphreyfellowship.org', 1, 1],
  ['Joint Japan World Bank Scholarship', 'joint-japan-world-bank-scholarship', 'United States', 'united-states', 'scholarship', 'Masters', 'full', 'Full funding', 'April 2026', 'The JJ/WBGSP supports mid-career professionals from developing countries to pursue graduate studies related to development.', 'Must be from a developing country. 3+ years development-related work experience. Under 45.', 'Full tuition, monthly stipend, travel, health insurance', 'Development-related fields', 'Various Universities', 'United States', 'https://worldbank.org/scholarships', 1, 1],
  ['American University Emerging Global Leader Scholarship', 'american-university-emerging-global-leader', 'United States', 'united-states', 'scholarship', 'Bachelors', 'full', 'Full funding', 'December 2025', 'This scholarship supports international students who demonstrate a commitment to public service and positive change in their home countries.', 'International student with financial need. Demonstrated leadership and commitment to community.', 'Full tuition, room and board, books', 'All disciplines', 'American University', 'United States', 'https://american.edu/admissions/international/emerging-global-leader.cfm', 1, 1],
  ['MasterCard Foundation at McGill', 'mastercard-foundation-mcgill', 'Canada', 'canada', 'scholarship', 'Masters', 'full', 'Full funding', 'January 2026', 'The Mastercard Foundation Scholars Program at McGill University supports academically talented yet financially disadvantaged young Africans.', 'Must be African. Demonstrate financial need and academic excellence. Commitment to give back to Africa.', 'Full tuition, housing, living stipend, books, airfare', 'All disciplines', 'McGill University', 'Canada', 'https://mcgill.ca/mastercardfoundation', 1, 1],

  // Germany
  ['Konrad Adenauer Foundation Scholarship', 'konrad-adenauer-foundation-scholarship', 'Germany', 'germany', 'scholarship', 'Masters,PhD', 'full', '€1,200/month', 'January 2026', 'The Konrad-Adenauer-Stiftung offers scholarships to highly talented foreign students for study and research in Germany.', 'Excellent academic record. Social and political engagement. Knowledge of German preferred.', 'Monthly stipend, study allowance, health insurance', 'All disciplines', 'Various German Universities', 'Germany', 'https://kas.de/en/web/begabtenfoerderung-und-kultur', 0, 1],
  ['Friedrich Ebert Foundation Scholarship', 'friedrich-ebert-foundation-scholarship', 'Germany', 'germany', 'scholarship', 'Masters,PhD', 'full', '€934/month', 'Ongoing', 'The Friedrich-Ebert-Stiftung supports students who are committed to the basic values of social democracy and show high academic performance.', 'Good academic performance. Political and social engagement. Any nationality.', 'Monthly stipend, health insurance, study allowance', 'All disciplines', 'Various German Universities', 'Germany', 'https://fes.de/studienfoerderung', 0, 0],
  ['Helmut Schmidt Programme', 'helmut-schmidt-programme', 'Germany', 'germany', 'scholarship', 'Masters', 'full', 'Full funding', 'February 2026', 'DAAD\'s Helmut Schmidt Programme supports public policy and good governance studies in Germany for development country professionals.', 'From developing country. 2+ years work experience in public sector. Good English/German.', 'Full tuition, monthly stipend, travel allowance, health insurance', 'Public Policy, Governance, Development', 'Various German Universities', 'Germany', 'https://daad.de/helmut-schmidt', 1, 1],

  // Netherlands
  ['Orange Tulip Scholarship', 'orange-tulip-scholarship', 'Netherlands', 'netherlands', 'scholarship', 'Bachelors,Masters', 'partial', 'Varies', 'January 2026', 'The Orange Tulip Scholarship (OTS) is offered by Nuffic Neso offices and Dutch universities to talented students from select countries.', 'Eligible nationality. Strong academic record. English proficiency.', 'Partial to full tuition waiver depending on university', 'All disciplines', 'Various Dutch Universities', 'Netherlands', 'https://studyinholland.nl/scholarships', 0, 1],
  ['Holland Scholarship', 'holland-scholarship', 'Netherlands', 'netherlands', 'scholarship', 'Bachelors,Masters', 'partial', '€5,000', 'February 2026', 'The Holland Scholarship is for international students from outside the European Economic Area who want to do a bachelor\'s or master\'s in the Netherlands.', 'Non-EEA student. Accepted at a Dutch university. Strong academic record.', '€5,000 one-time payment', 'All disciplines', 'Various Dutch Universities', 'Netherlands', 'https://studyinholland.nl/scholarships/holland-scholarship', 0, 0],

  // Australia
  ['Destination Australia Scholarship', 'destination-australia-scholarship', 'Australia', 'australia', 'scholarship', 'Bachelors,Masters,PhD', 'partial', 'AUD 15,000/year', 'Varies', 'Destination Australia supports international and domestic students to study in regional Australia, encouraging population growth outside major cities.', 'Enrolled at a participating regional Australian institution. Strong academic merit.', 'Up to AUD 15,000 per year', 'All disciplines', 'Various Regional Australian Universities', 'Australia', 'https://education.gov.au/destination-australia', 0, 0],
  ['Endeavour Leadership Programme', 'endeavour-leadership-programme', 'Australia', 'australia', 'scholarship', 'Masters,PhD', 'full', 'Full funding', 'June 2026', 'The Endeavour Leadership Programme provides merit-based scholarships for international citizens to study in Australia.', 'Strong academic record. Leadership qualities. From eligible country.', 'Tuition, travel, establishment, monthly stipend, health insurance', 'All disciplines', 'Various Australian Universities', 'Australia', 'https://dfat.gov.au/endeavour', 1, 0],

  // Norway/Scandinavia
  ['Norwegian Government Quota Scholarship', 'norwegian-government-quota-scholarship', 'Norway', 'norway', 'scholarship', 'Masters,PhD', 'full', 'Full funding', 'December 2025', 'The Norwegian Government offers quota scholarships for students from developing countries to study at Norwegian universities.', 'From a developing country on the quota list. Accepted at a Norwegian university.', 'Tuition waiver, monthly stipend, travel grant, health insurance', 'All disciplines', 'Various Norwegian Universities', 'Norway', 'https://hkdir.no/en/grants-and-loans/quota-scheme', 1, 1],
  ['Swedish Institute Scholarships', 'swedish-institute-scholarships', 'Sweden', 'sweden', 'scholarship', 'Masters', 'full', 'Full funding', 'February 2026', 'The Swedish Institute offers scholarships to future leaders who wish to pursue Master\'s studies in Sweden and make a difference in their home countries.', 'From an eligible country. Bachelor\'s degree. Work experience preferred. Leadership skills.', 'Tuition, living expenses, travel, insurance', 'All disciplines', 'Various Swedish Universities', 'Sweden', 'https://si.se/en/apply/scholarships', 1, 1],

  // China
  ['Chinese Government Scholarship', 'chinese-government-scholarship', 'China', 'china', 'scholarship', 'Bachelors,Masters,PhD', 'full', 'Full funding', 'March 2026', 'The Chinese Government Scholarship Programme is jointly established by the Chinese Government and governments of other countries to sponsor international students.', 'Under 25 for bachelor\'s, under 35 for master\'s, under 40 for PhD. Good health. No current study in China.', 'Tuition waiver, accommodation, monthly stipend, medical insurance', 'All disciplines', 'Various Chinese Universities', 'China', 'https://campuschina.org', 1, 1],
  ['Confucius Institute Scholarship', 'confucius-institute-scholarship', 'China', 'china', 'scholarship', 'Bachelors,Masters', 'full', 'Full funding', 'Varies', 'The Confucius Institute Scholarship supports international students and Chinese language teachers to study in China.', 'Recommended by a Confucius Institute. Non-Chinese citizen. Good health.', 'Tuition, accommodation, monthly stipend, medical insurance', 'Chinese language and culture', 'Various Chinese Universities', 'China', 'https://cis.chinese.cn', 0, 0],

  // Japan
  ['JICA Scholarship', 'jica-scholarship', 'Japan', 'japan', 'scholarship', 'Masters', 'full', 'Full funding', 'Varies', 'JICA (Japan International Cooperation Agency) offers scholarships for students from developing countries to study in Japan in development-related fields.', 'Government-nominated from developing country. Work experience in relevant field. Under 40.', 'Tuition, living allowance, travel, insurance', 'Development studies, engineering, agriculture, health', 'Various Japanese Universities', 'Japan', 'https://jica.go.jp/english/our_work/social_environmental/education', 0, 1],
  ['ADB Japan Scholarship', 'adb-japan-scholarship', 'Japan', 'japan', 'scholarship', 'Masters', 'full', 'Full funding', 'Varies by university', 'The ADB-Japan Scholarship Program offers scholarships to citizens of ADB developing member countries for postgraduate studies in economics, management, science and technology.', 'Citizen of ADB developing member country. Bachelor\'s degree. 2+ years work experience. Under 35.', 'Tuition, monthly allowance, housing, airfare, health insurance', 'Economics, Management, Science, Technology', 'Various ADB partner universities', 'Japan', 'https://adb.org/site/careers/japan-scholarship-program', 0, 1],

  // Turkey
  ['TIKA Scholarship', 'tika-scholarship', 'Turkey', 'turkey', 'scholarship', 'Bachelors,Masters', 'full', 'Full funding', 'March 2026', 'Turkish Cooperation and Coordination Agency (TIKA) offers scholarships for students from developing countries to study in Turkey.', 'From a developing country with TIKA cooperation. Strong academic record.', 'Tuition, accommodation, monthly stipend, health insurance', 'All disciplines', 'Various Turkish Universities', 'Turkey', 'https://tika.gov.tr', 0, 0],

  // Belgium
  ['VLIR-UOS Scholarship', 'vlir-uos-scholarship', 'Belgium', 'belgium', 'scholarship', 'Masters', 'full', 'Full funding', 'February 2026', 'VLIR-UOS offers scholarships for students from developing countries to study a Master\'s programme at a Flemish university in Belgium.', 'Citizen of eligible developing country. Bachelor\'s degree. Proficiency in English or Dutch.', 'Full tuition, monthly allowance, travel, insurance', 'Development-related disciplines', 'Various Flemish Universities', 'Belgium', 'https://vliruos.be/en/scholarships', 1, 1],

  // France
  ['Eiffel Excellence Scholarship', 'eiffel-excellence-scholarship', 'France', 'france', 'scholarship', 'Masters,PhD', 'full', '€1,400/month', 'January 2026', 'The Eiffel Excellence Scholarship Programme was established by the French Ministry for Europe and Foreign Affairs to attract top foreign students to France.', 'Under 30 for master\'s, under 35 for PhD. Excellent academic record. Non-French.', 'Monthly allowance, repatriation costs, health insurance, cultural activities', 'Engineering, Economics, Law, Political Science', 'Various French Universities', 'France', 'https://campusfrance.org/en/eiffel-scholarship-program-of-excellence', 1, 1],

  // South Korea
  ['Korean Government Scholarship (GKS)', 'korean-government-scholarship-gks', 'South Korea', 'south-korea', 'scholarship', 'Bachelors,Masters,PhD', 'full', 'Full funding', 'March 2026', 'The Korean Government Scholarship Program (GKS/KGSP) supports international students to study at Korean universities.', 'Non-Korean citizen. Under 25 for bachelor\'s. Strong academic record. Good health.', 'Tuition, monthly allowance, airfare, Korean language training', 'All disciplines', 'Various Korean Universities', 'South Korea', 'https://studyinkorea.go.kr', 1, 1],

  // Africa-based
  ['African Development Bank Scholarship', 'african-development-bank-scholarship', 'Various', 'various', 'scholarship', 'Masters', 'full', 'Full funding', 'April 2026', 'The African Development Bank offers scholarships to African students for postgraduate studies at leading universities worldwide.', 'African citizen. Bachelor\'s with distinction. Under 35. Strong commitment to Africa\'s development.', 'Full tuition, living allowance, travel, insurance', 'Development-related fields', 'Partner Universities Worldwide', 'Various', 'https://afdb.org/en/topics-and-sectors/initiatives-partnerships/african-development-bank-scholarship-program', 1, 1],
  ['Aga Khan Foundation International Scholarship', 'aga-khan-foundation-international-scholarship', 'Various', 'various', 'scholarship', 'Masters', 'partial', '50% grant + 50% loan', 'March 2026', 'The Aga Khan Foundation International Scholarship Programme provides scholarships for postgraduate studies to outstanding students from developing countries.', 'From a developing country. Financial need. Excellent academic record. No other funding source.', '50% grant and 50% loan for tuition and living expenses', 'All disciplines', 'Various Universities Worldwide', 'Various', 'https://akdn.org/agency/akf/scholarships-fellowships', 1, 1],
  ['PAASCU Scholarship', 'african-union-scholarship', 'Various', 'various', 'scholarship', 'Masters,PhD', 'full', 'Full funding', 'June 2026', 'The African Union Commission offers scholarships for African students to study in African universities or abroad in strategic fields.', 'African Union member state citizen. Strong academic performance. Commitment to African development.', 'Full tuition, monthly stipend, airfare, insurance', 'STEM, Agriculture, Health, Governance', 'Various African Universities', 'Various', 'https://au.int/en/scholarships', 0, 1],
  ['WACSI Fellowship', 'wacsi-fellowship', 'Ghana', 'ghana', 'fellowship', 'Non-degree', 'full', 'Full funding', 'Ongoing', 'The West Africa Civil Society Institute (WACSI) offers fellowships for civil society practitioners from West Africa to strengthen their capacity.', 'West African civil society practitioner. 3+ years experience. Commitment to social change.', 'Training, mentorship, networking, stipend', 'Civil Society, Governance, Development', 'WACSI Ghana', 'Ghana', 'https://wacsi.org', 0, 0],

  // Global/International
  ['Erasmus Mundus Joint Masters', 'erasmus-mundus-joint-masters', 'Various', 'various', 'scholarship', 'Masters', 'full', '€1,400/month', 'October 2025', 'Erasmus Mundus Joint Master Degrees are high-level integrated study programmes offered by international consortia of higher education institutions.', 'Bachelor\'s degree. Varies by programme. Strong academic record. English proficiency.', 'Monthly allowance, tuition waiver, travel and installation costs', 'Varies by programme', 'Multiple European Universities', 'Various', 'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters', 1, 1],
  ['Commonwealth Split-Site PhD Scholarship', 'commonwealth-split-site-phd', 'United Kingdom', 'united-kingdom', 'scholarship', 'PhD', 'full', 'Full funding', 'October 2025', 'Commonwealth Split-Site Scholarships enable PhD students from developing countries to spend 12 months at a UK university as part of their PhD.', 'Registered PhD student in eligible Commonwealth country. University nomination required.', 'Airfare, tuition, living expenses for 12 months in UK', 'All disciplines', 'Any UK University', 'United Kingdom', 'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-split-site-scholarships', 0, 1],
  ['OPEC Fund Scholarship', 'opec-fund-scholarship', 'Various', 'various', 'scholarship', 'Masters', 'full', 'Full funding', 'March 2026', 'The OPEC Fund for International Development offers scholarships to students from member or beneficiary countries to pursue postgraduate degrees.', 'Citizen of OPEC Fund member or beneficiary country. Under 32. Good academic record.', 'Full tuition, monthly stipend, travel, health insurance', 'Energy, economics, engineering, environmental studies', 'Top International Universities', 'Various', 'https://opecfund.org/scholarships', 0, 1],
  ['World Bank Global Scholarship Program', 'world-bank-global-scholarship', 'United States', 'united-states', 'scholarship', 'Masters', 'full', 'Full funding', 'January 2026', 'The World Bank Group offers scholarships to support mid-career professionals from developing countries to pursue graduate studies.', 'From developing country. 3+ years relevant work experience. Commitment to return home.', 'Full tuition, living stipend, travel, health insurance', 'Development-related fields', 'Various Top Universities', 'Various', 'https://worldbank.org/scholarships', 0, 1],
  ['Ford Foundation Fellowship', 'ford-foundation-fellowship', 'United States', 'united-states', 'fellowship', 'PhD', 'full', 'Full funding', 'December 2025', 'The Ford Foundation Fellowship Programs seek to increase the diversity of the nation\'s college and university faculties by increasing their ethnic and racial diversity.', 'Committed to diversity and equal opportunity. Pursuing academic career. US citizen or national.', 'Annual stipend, research allowance, access to Ford Fellows conferences', 'All disciplines', 'Various US Universities', 'United States', 'https://nasonline.org/programs/ford-fellowships', 0, 0],
  ['Soros Equality Fellowship', 'soros-equality-fellowship', 'United States', 'united-states', 'fellowship', 'Non-degree', 'full', '$85,000', 'October 2025', 'The Soros Equality Fellowship supports advocates working to advance racial justice and equality in the United States.', 'Demonstrated commitment to racial justice. Working in US. Innovative approach to systemic change.', '$85,000 stipend over 18 months, professional development, network access', 'Racial justice, civil rights, social justice', 'Open Placement', 'United States', 'https://opensocietyfoundations.org/fellowships/soros-equality-fellowship', 0, 0],
  ['USAID Donald M Payne Fellowship', 'usaid-donald-payne-fellowship', 'United States', 'united-states', 'fellowship', 'Masters', 'full', 'Full funding', 'November 2025', 'The Donald M. Payne International Development Fellowship Program seeks to attract talented US citizens who are interested in pursuing a career in the US Foreign Service.', 'US citizen. Financial need. Strong interest in international development. Under 30.', 'Full tuition, stipend, internships, mentoring', 'International Development, Public Policy', 'Various US Universities', 'United States', 'https://paynefellows.org', 0, 0],

  // Internships
  ['African Development Bank Internship', 'african-development-bank-internship', 'Various', 'various', 'internship', 'Bachelors,Masters', 'paid', '$700-1000/month', 'Ongoing', 'The African Development Bank Group Internship Program provides an opportunity for undergraduate and graduate students to gain practical experience.', 'African or non-African student enrolled in undergraduate or graduate program. Strong academic record.', 'Monthly stipend, work experience at major development institution', 'Economics, finance, engineering, social sciences', 'African Development Bank HQ', 'Various', 'https://afdb.org/en/careers/internships', 0, 1],
  ['UN Secretariat Internship', 'un-secretariat-internship', 'United States', 'united-states', 'internship', 'Bachelors,Masters', 'paid', 'Stipend available', 'Ongoing', 'The United Nations Secretariat offers internship opportunities at various duty stations around the world for students pursuing degrees in fields related to UN work.', 'Enrolled in graduate or undergraduate programme. Fluent in at least one UN language. Strong academic record.', 'Work experience, networking, UN grounds access, some with stipend', 'Various fields related to UN mandate', 'UN Headquarters and Field Offices', 'United States', 'https://careers.un.org/lbw/home.aspx?viewtype=IP', 0, 1],
  ['World Health Organization Internship', 'who-internship', 'Switzerland', 'switzerland', 'internship', 'Masters', 'paid', 'CHF 250/week', 'Ongoing', 'WHO offers internships to provide a diverse group of students with the opportunity to gain professional experience in an international environment.', 'Enrolled in master\'s or PhD programme in health or related field. Under 30. Fluent in at least one WHO official language.', 'Weekly stipend, professional experience, international networking', 'Public health, medicine, sciences, communications', 'WHO Geneva and Regional Offices', 'Switzerland', 'https://who.int/careers/internships', 0, 1],
  ['IMF Internship Program', 'imf-internship-program', 'United States', 'united-states', 'internship', 'Masters,PhD', 'paid', '$3,500/month', 'Ongoing', 'The IMF offers internship opportunities for graduate students to gain hands-on experience in international economics and finance.', 'PhD or advanced master\'s student in economics or finance. Strong quantitative skills.', '$3,500/month, professional development, IMF network access', 'Economics, Finance, Statistics', 'IMF Washington DC', 'United States', 'https://imf.org/en/About/Recruitment/internship', 0, 1],

  // Research Grants
  ['Carnegie African Diaspora Fellowship', 'carnegie-african-diaspora-fellowship', 'Various', 'various', 'research-grant', 'PhD', 'full', 'Full funding', 'Ongoing', 'The Carnegie African Diaspora Fellowship Program provides grants for short-term projects at African higher education institutions, led by African-born academics.', 'African-born faculty member at US or Canadian university. Project at African institution.', 'Travel, accommodation, project support for 14-90 day visit', 'All academic disciplines', 'African Universities', 'Various', 'https://africandiasporafellowship.org', 0, 0],
  ['TDR Research Training Grants', 'tdr-research-training-grants', 'Various', 'various', 'research-grant', 'Masters,PhD', 'full', 'Full funding', 'Ongoing', 'TDR, the Special Programme for Research and Training in Tropical Diseases, offers research training grants for scientists from low-income countries.', 'Scientist or health professional from low-income country. Conducting research on infectious diseases of poverty.', 'Research funding, training, mentorship', 'Tropical diseases, global health, infectious diseases', 'Various Research Institutions', 'Various', 'https://tdr.who.int/funding-opportunities', 0, 0],
  ['Wellcome Trust African Programmes', 'wellcome-trust-african-programmes', 'Various', 'various', 'research-grant', 'Masters,PhD', 'full', 'Full funding', 'Ongoing', 'Wellcome Trust offers various funding schemes for African scientists to conduct biomedical and health research across Africa.', 'African scientist at an African institution. Conducting research relevant to African health priorities.', 'Research funding, capacity building, institutional support', 'Biomedical sciences, global health, public health', 'African Research Institutions', 'Various', 'https://wellcome.org/grant-funding/schemes/african-research', 0, 1],
];

async function seedMore() {
  console.log(`Adding ${scholarships.length} scholarships...`);
  let added = 0, skipped = 0;

  for (const [title, slug, country, country_slug, type, degree_level, funding_type, amount, deadline, description, eligibility, benefits, subjects, host_university, host_country, official_url, visa_sponsored, is_featured] of scholarships) {
    try {
      const existing = await db.execute({ sql: 'SELECT id FROM scholarships WHERE slug = ?', args: [slug] });
      if (existing.rows.length) { skipped++; continue; }
      await db.execute({
        sql: `INSERT INTO scholarships (title, slug, country, country_slug, type, degree_level, funding_type, amount, deadline, description, eligibility, benefits, subjects, host_university, host_country, official_url, visa_sponsored, is_featured, is_approved, is_active) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 1)`,
        args: [title, slug, country, country_slug, type, degree_level, funding_type, amount, deadline, description, eligibility, benefits, subjects, host_university, host_country, official_url, visa_sponsored ? 1 : 0, is_featured ? 1 : 0],
      });
      added++;
    } catch (e) {
      console.error(`Failed: ${title}`, e.message);
      skipped++;
    }
  }

  console.log(`✅ Done! Added: ${added}, Skipped: ${skipped}`);
  process.exit(0);
}

seedMore().catch(err => { console.error(err); process.exit(1); });
